config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get '/home/contact', to: 'home#contact'

  namespace :admin do
    resources :main
    resources :posts
    resources :users
    get '/main/index', to: 'main#index'
  end

  # resources :posts
  resources :posts do
    get 'order_by', on: :collection
    post 'create_comment', on: :collection
    delete 'destroy_comment', on: :collection
  end

  get 'author_posts', to: 'posts#author_posts'
  get 'categories', to: 'posts#categories'

  devise_for :users
end

app/models/post.rb
class Post < ApplicationRecord

  has_rich_text :content

  belongs_to :user
  has_many :comments, dependent: :destroy

  before_create :set_default_status

  enum status: [:draft, :published]
  def set_default_status
    self.status ||= :draft
  end

  # ====================================================================================================================
  def self.filter params
    conditions = []
    values = {}
    unless params[:title].blank?
      conditions << 'LOWER("title") LIKE :title'
      values[:title] = "%#{params[:title].to_s.downcase}%"
    end
    return [conditions.join(' AND '), values] unless values.empty?
  end

  def self.get_category_post params, category
    self.where(category: category).order("created_at DESC").paginate(page: params[:page], per_page: 3)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_user, :admin?
  before_action :set_post, only: [:show, :show_draft]

  layout 'admin'
  # ====================================================================================================================
  def index
    query = Post.filter params
    @posts = Post.where(query).order("created_at DESC").paginate(page: params[:page], per_page: 10)
  end
  # ====================================================================================================================
  def show
    @comment = @post.comments.new unless @post.blank?
    @comments = Comment.where(post_id: @post).order("created_at ASC")
  end
  # ====================================================================================================================
  def show_draft
  end
  # ====================================================================================================================
  # PRIVATE ============================================================================================================
  # ====================================================================================================================
  private
  def set_post
    @post = Post.find_by_id params[:id]
  end
  # ====================================================================================================================
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [ :update, :destroy, :destroy_comment  ], except: :index
  before_action :require_user, :admin?, only: [ :update, :destroy, :destroy_comment  ], except: :index
  before_action :set_post, only: %i[ newest_comments author_posts show edit update create_comment destroy destroy_comment ]
  before_action :set_comment, only: [:newest_comments, :show, :create_comment ]

  # ====================================================================================================================
  def index
    query = Post.filter params
    @posts = Post.where(query).where(status: :published).order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end
  # ====================================================================================================================
  def show
    @comment = @post.comments.new unless @post.blank?
    @comments = Comment.where(post_id: @post).order(params[:sort] ||= 'created_at ASC')
  end
  # ====================================================================================================================
  def new
    @post = Post.new
  end
  # ====================================================================================================================
  def edit;end
  # ====================================================================================================================
  def categories
    @posts = params[:category].blank? ? Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 5) : Post.get_category_post(params, params[:category])
  end
  # ====================================================================================================================
  def author_posts
    @user = @post.user
    @posts = @user.posts.order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end
  # ====================================================================================================================
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: Translate.created_msg(controller_name.classify) }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  # ====================================================================================================================
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: Translate.updated_msg(controller_name.classify) }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  # ====================================================================================================================
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: Translate.destroyed_msg(controller_name.classify) }
      format.json { head :no_content }
    end
  end

  # ====================================================================================================================
  # COMMENT ============================================================================================================
  # ====================================================================================================================
  def create_comment
    @post = Post.find_by_id params[:comment][:post_id]
    @comment = @post.comments.new(comment_params)
    @texto = I18n.t('comment.error.creating')

    if @comment.save
      @texto = I18n.t('comment.successfully.created')
    end
    respond_to do |f|
      f.html { redirect_to post_url(@post), notice: @texto }
      f.json { render json: @post.errors, status: :unprocessable_entity }
    end
  end
  # ====================================================================================================================
  def destroy_comment
    # @post = Post.find_by_id params[:comment][:post_id]
    @comment = Comment.find_by_id params[:id]

    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: I18n.t('comment.successfully.destroyed') }
      format.json { head :no_content }
    end
  end
  # FIM COMMENT ========================================================================================================

  # ====================================================================================================================
  # PRIVATE ============================================================================================================
  # ====================================================================================================================
  private
  def set_post
    @post = Post.find_by_id params[:id]
  end
  # ====================================================================================================================
  def set_comment
    @comment = Comment.find_by_id params[:post_id]
  end
  # ====================================================================================================================
  def post_params
    params.require(:post).permit(:title, :body, :user_id, :status)
  end
  # ====================================================================================================================
  def comment_params
    params.require(:comment).permit(:name, :body, :post_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def badge_color status
    badge = "badge badge-pill bg"
    case status
    when "draft"
      "#{badge}-warning"
    when "published"
      "#{badge}-primary"
    end
  end
  # ====================================================================================================================
  def post_categories # todo: most viwed!
    Post.all.where('top < 6').order('top ASC').limit(5)
  end
end

app/views/posts/partials/_comments.html.erb
<% if comments.count > 0 %>
  <% comments.each do |comment|
    # side = "left"
    # side = 'right' if my_perfil?(@current_user, comment.user)
  %>
    <div class="row mt20 margin-nil">
      <div class="chat-discussion chat-discussion-support">
        <div class="chat-message">
          <!--          <img class="message-avatar" id="imagem-perfil" src="<%#= image_path(media.nil? ? "logo-temp.png" : media.get_aws_url) %>" alt="Avatar">-->
          <div class="message">
            <div class="d-flex justify-content-between">
              <a class="message-author" href="#"> <%= comment.name %> </a>
              <p class="message-date"> <%= l(comment&.created_at, format: :long) %> </p>
            </div>
            <div class="d-flex justify-content-between">
              <span class="message-content"> <%= comment&.body.html_safe %> </span>
              <% if signed_in? && current_user.user_type == :admin %>
                <%= link_to fa_icon("trash"), destroy_comment_posts_path(id: comment), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: t('confirm.destroy') } %>
              <% end %>
            </div>
            <hr>
          </div>
        </div>
      </div>
    </div>
  <%
    end
  end
  %>

app/views/posts/partials/_form.html.erb
<%= form_with(model: post, local: true) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :status, value: :draft %>
  <div class="form-group mt-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", type: "text", placeholder: t('general.name') %>
  </div>
  <div class="form-group mt-3">
    <%= f.label :body %>
    <%= f.rich_text_area :body, class: "form-control", type: "text", placeholder: "Texto" %>
  </div>
  <% if current_user.user_type == "admin" %>
    <div class="form-group mt-3">
      <label><%= t('table.type') %>:</label>
      <%= f.label :status %>
      <% status_post = [[t('activerecord.attributes.statuses.draft'), :draft], [t('activerecord.attributes.statuses.published'), :published]] %>
      <%= f.select :status, status_post, class: "form-control input-sm", type: "text", placeholder: t('table.status') %>
    </div>
  <% end %>
  <div class="form-group mt-3">
    <%= f.submit t('btn.save'), class: "btn btn-sm btn-primary pull-right m-t-n-xs", value: t('btn.save') %>
  </div>

  <div class="clearfix"></div>
<% end %>

app/views/posts/partials/_new_comment.html.erb
<div id="support_status_updated" class="row">
  <div class="col-xs-12 form-group">
    <div class="form-group mt-4" style="margin-bottom:0;">
      <%= form_for(@comment, url: create_comment_posts_path, html: { class: "form valida-form", role: "form", method: "post"}) do |f| %>
        <%= f.hidden_field :post_id, value: @post.id %>

        <div class="form-group">
          <%= f.label :body %>
          <%= f.rich_text_area :body, class: "form-control", placeholder: t('comment.enter.comment') %>

          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: t('comment.enter.name') %>
          <br>
          <div class="d-flex justify-content-between align-items-center">
            <%= link_to 'Back', posts_path, class: "btn btn-sm btn-dark pull-right m-t-n-xs mt-2" %>
            <%= f.submit t('btn.save'), class: "btn btn-sm btn-primary pull-right m-t-n-xs mt-2", value: t('btn.save') %>
          </div>
        </div>
        <div class="clearfix"></div>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/partials/_posts.html.erb
<hr class="post-title margin-hr">
<% posts.each do |post| %>
  <div>
    <p><%= post&.title %></p>
    <span>
    <%= truncate(post&.body, length: 300) %><br>
      <%= link_to t('post.see_more'), post, class: 'text-purple' %>
  </span>
    <span class="pull-right">
  <%= t('post.author') %>: <%= link_to post.user&.name, author_posts_path(id: post), class: 'text-purple'%>
  </span> <br />
    <p> <hr class="post margin-hr"> </p>
  </div>
  <% if signed_in? && current_user.user_type == :admin %>
    <h2><%= link_to t('btn.edit'), edit_post_path(post) %></h2>
    <h2><%= link_to t('btn.delete'), post, method: :delete, data: { confirm: t('confirm.destroy') } %></h2>
  <% end %>
<% end %>
<div class="mb-5 d-flex justify-content-end">
  <div class="mb-5 style-pagination">
    <%= will_paginate posts, previous_label: fa_icon('angle-left', text: t('will_paginate.prev')), next_label: t('will_paginate.next', icon: fa_icon('angle-right')) %>
  </div>
</div>