config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get '/home/contact', to: 'home#contact'

  namespace :admin do
    resources :main
    resources :posts
    resources :users
    get '/main/index', to: 'main#index'
  end

  # resources :posts
  resources :posts do
    get 'order_by', on: :collection
    post 'create_comment', on: :collection
    delete 'destroy_comment', on: :collection
  end

  get 'author_posts', to: 'posts#author_posts'
  get 'categories', to: 'posts#categories'

  devise_for :users
end

app/views/shared/_footer.html.erb
<div>
  <a class="px-2" href="https://www.linkedin.com/company/nucleusapp" target="_blank"><%= fa_icon("linkedin") %></a>
  <a class="px-2" href="https://www.instagram.com/nucleusapp/" target="_blank"><%= fa_icon("instagram") %></a>
  <a class="px-2" href="https://wa.me/554799999709" target="_blank" height="auto"> <%= fa_icon("whatsapp") %> </a>
</div>
<bloquote class="">
  <small> <b>Copyright</b>
    <a href="https://appnucleus.com.br/">Nucleus</a>
    <%= Time.current.year %>&copy; - <%= t('general.copyright') %>
  </small>
</bloquote>

app/views/shared/_header.html.erb
<b class="logo-icon"><%= link_to image_tag('logo.png', width:'80', alt:'Nucleus'), root_path %></b>
<div class="ms-3 col-lg-4 col-md-4 col-xs-4">

  <nav>
    <ul class="nav flex nav-pills">
      <% if signed_in? && current_user.user_type == "admin" %>
        <li class="nav-item">
          <%= link_to "Admin", admin_main_index_path, class: "nav-link #{"active" if params[:controller] == "admin/main"}" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link #{"active" if params[:controller] == "home" && params[:action] == "index"}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Posts", posts_path, class: "nav-link #{"active" if params[:controller] == "posts"}" %>
      </li>
      <li class="nav-item">
        <%= link_to t('general.contact'), home_contact_path, class: "nav-link #{"active" if params[:action] == "contact"}" %>
      </li>
    </ul>
  </nav>

  <a class="nav-toggler waves-effect d-block d-md-none" href="javascript:void(0)"> <i class="ti-menu ti-close"></i> </a>
</div>

<div class="navbar-collapse collapse" id="">
  <div class="navbar-nav ms-auto">
    <div class=" in">
      <% if params[:action] == "index" && params[:controller] == "admin/users" || params[:controller] == "admin/posts" || params[:controller] == "posts" %>
        <form role="search" class="app-search d-none d-md-block me-2">
          <%= get_filter %> <a href="" class="active"> <i class="fa fa-search me-4"></i> </a>
        </form>
      <% end %>
    </div>
  </div>

  <div class="col-lg-1">
    <div class="btn-group text-white">
      <button class="btn btn-default bg-purple">
        <span>
          <img src="<%= image_path("user-solid.svg") %>" alt="user-img" width="20" class="img-circle">
        </span>
      </button>
      <button class="btn btn-default dropdown-toggle text-white" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        <%= fa_icon("caret-down") %>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <% if signed_in? %>
          <li><%= link_to "Admin", admin_main_index_path, class: 'dropdown-item' %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", "/users/sign_in", class: 'dropdown-item' %></li>
          <li><%= link_to "Sign up", "/users/sign_up", class: 'dropdown-item' %></li>
        <% end %>
      </ul>
    </div>
  </div>

</div>

</div>

app/views/shared/_navbar_left.erb
<nav>
  <div class="border border-2 p-2 bg-gray">
    <h5 class="ms-2"><%= t('activerecord.attributes.post.category.other') %></h5>
    <ul class="nav flex-column nav-pills">
      <li class="nav-item">
        <%= link_to t('activerecord.attributes.post.categories.technology'),
                    categories_path(category: "Tecnologia"), class: "nav-link #{"active" if params[:category] == "Tecnologia"}"
        %>
      </li>
      <li class="nav-item">
        <%= link_to t('activerecord.attributes.post.categories.financial'),
                    categories_path(category: "Financeiro"), class: "nav-link #{"active" if params[:category] == "Financeiro"}"
        %>
      </li>
      <li class="nav-item">
        <%= link_to t('activerecord.attributes.post.categories.graphic'),
                    categories_path(category: "Gráfica"), class: "nav-link #{"active" if params[:category] == "Gráfica"}"
        %>
      </li>
      <li class="nav-item">
        <%= link_to t('activerecord.attributes.post.categories.culture'),
                    categories_path(category: "Cultura"), class: "nav-link #{"active" if params[:category] == "Cultura"}"
        %>
      </li>
    </ul>
  </div>
  <div class="mt-4 border border-2 p-2 bg-gray">
    <h5 class="ms-2"><%= t('post.top') %></h5>
    <ul>
      <li class="nav-item mb-5">
        <% i = 0 %>
        <% post_categories.each do |c| %>
          <div class="ps-2 py-1">
            <span class="h5 font-bold"><%= i+=1 %> &#160;</span>
            <span><%= c.title %></span>
            <p><small style="color: lightslategray"><%= l(c.created_at, format: :default_short) %></small></p>
          </div>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_system_alerts.html.erb
<%
  alert_class = ""
  flash.each do |type, message|
    case type.to_s
    when "success"
      alert_class = "alert-success"
    when "error"
      alert_class = "alert-danger"
    when "alert"
      alert_class = "alert-warning"
    when "notice"
      alert_class = "alert-info"
    else
      alert_class = "alert-secondary"
    end
%>
  <div class="alert <%= alert_class %>">
    <%= message %>
    <button type="button" class="btn-close float-right" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>