config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get '/home/contact', to: 'home#contact'

  namespace :admin do
    resources :main
    resources :posts
    resources :users
    get '/main/index', to: 'main#index'
  end

  # resources :posts
  resources :posts do
    get 'order_by', on: :collection
    post 'create_comment', on: :collection
    delete 'destroy_comment', on: :collection
  end

  get 'author_posts', to: 'posts#author_posts'
  get 'categories', to: 'posts#categories'

  devise_for :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  before_create :set_default_user_type

  enum user_type: [:user, :admin]
  def set_default_user_type
    self.user_type ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  # ====================================================================================================================
  private

  def self.filter params
    conditions = []
    values = {}
    unless params[:name].blank?
      conditions << 'LOWER("name") LIKE :name'
      values[:name] = "%#{params[:name].to_s.downcase}%"
    end
    return [conditions.join(' AND '), values] unless values.empty?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_user, :admin?
  before_action :set_user, only: [ :show, :edit, :update, :destroy ]
  layout 'admin'
  # ====================================================================================================================
  def index
    query = User.filter params
    @users = User.where(query).order('created_at DESC').paginate(page: params[:page], per_page: 8)
  end
  # ====================================================================================================================
  def show
  end
  # ====================================================================================================================
  def new
    @user = User.new
  end
  # ====================================================================================================================
  def edit
  end
  # ====================================================================================================================
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: Translate.created_msg(controller_name.classify) }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # ====================================================================================================================
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to "/", notice: Translate.updated_msg(controller_name.classify) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # ====================================================================================================================
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: Translate.destroyed_msg(controller_name.classify) }
      format.json { head :no_content }
    end
  end

  # ====================================================================================================================
  # PRIVATE! ===========================================================================================================
  # ====================================================================================================================
  private
  def set_user
    @user = User.find_by_id params[:id]
  end
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :user_type)
  end
end

app/views/admin/users/edit.html.erb
<h1><%= editing_model %></h1>

<%= render 'admin/users/partials/form', user: @user %>

<%= link_to 'Show', admin_users_path(@user) %>
<%= link_to 'Back', admin_users_url %>

app/views/admin/users/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <div>
    <h1 class="mt-4 h2"><%= t('activerecord.models.user.other') %></h1>
    <hr class="post-title margin-hr">
  </div>
  <%= link_to t('general.new_model', model: t('activerecord.models.user.one')), new_admin_user_path, class: 'btn btn-primary btn-sm' %>
</div>
<table class="table table-stripped">
  <thead>
    <tr class="align-items-center">
      <th><%= t('general.name') %></th>
      <th><%= t('activerecord.attributes.user.email') %></th>
      <th><%= t('activerecord.attributes.user.user_type') %></th>
      <th class="text-center" width="120px"><%= t('general.actions') %></th>
    </tr>
  </thead>
  <tbody>
  <% if @users.count > 0
    @users.each do |user| %>
    <tr>
      <td><%= user&.name %></td>
      <td><%= user&.email %></td>
      <td><%= t("activerecord.attributes.user.user_types.#{user.user_type}") %></td>
      <td class="right">
        <%= link_to fa_icon("eye"), admin_user_path(user), class: "btn btn-xs btn-success" %>
        <%= link_to fa_icon("edit"), edit_admin_user_path(user), class: "btn btn-xs btn-primary" %> <%# todo! %>
        <%= link_to fa_icon("trash"), admin_user_path(user), class: "btn btn-xs btn-danger", method: :delete, data: { confirm: t('confirm.destroy') } %>
      </td>
    </tr>
    <% end %>
    </tbody>
  <% else %>
    <tr>
      <td colspan="10"> <p class="bg-info" style="padding:5px; margin:0;"><%= t('general.no_register_found') %></p> </td>
    </tr>
  <% end %>
</table>
<div class="mb-5 d-flex justify-content-end">
  <div class="mb-5 style-pagination">
    <%= will_paginate @users, previous_label: fa_icon('angle-left', text: t('will_paginate.prev')), next_label: t('will_paginate.next', icon: fa_icon('angle-right')) %>
  </div>
</div>

app/views/admin/users/new.html.erb
<h1><%= new_model %></h1>

<%= render 'admin/users/partials/form' %>

app/views/admin/users/show.html.erb
<div class="mt-3 container d-flex justify-content-center">
  <div class="container blog col-lg-9 col-md-10 col-sm-12 col-xs-12">
    <div class="d-flex justify-content-between align-items-center">
      <h1 class="mt-4"><%= t('activerecord.models.user.one') %><%= fa_icon('angle-right', text: @user&.id) %></h1>
      <span><%= link_to t('general.back'), admin_users_path, class: 'text-white btn btn-dark text-purple mt-3' %></span>
    </div>
    <hr class="post-title margin-hr">
    <p class="col-lg-12 col-md-6 col-xs-6"><b>ID: </b> <%= @user&.id %> </p>
    <p class="col-lg-12 col-md-6 col-xs-6"><b><%= t('general.name') %>: </b> <%= @user&.name %> </p>
    <p class="col-lg-12 col-md-6 col-xs-6"><b><%= t('activerecord.attributes.user.email') %>: </b> <%= @user&.email %> </p>
    <p class="col-lg-12 col-md-6 col-xs-6"><b><%= t('activerecord.attributes.user.created_at') %>: </b> <%= l(@user&.created_at, format: :long) %> </p>

    <p> <hr class="mt-3 post margin-hr"> </p>
  </div>
</div>